version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: laravel-app
    container_name: content_scheduler_app
    restart: unless-stopped
    working_dir: /var/www
    volumes:
      - ./:/var/www
    env_file:
      - .env
    networks:
      - laravel
    expose:
      - "9000"

  webserver:
    image: nginx:alpine
    container_name: content_scheduler_nginx
    restart: unless-stopped
    ports:
      - "80:80"
    volumes:
      - ./public:/var/www/public
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - app
    networks:
      - laravel

networks:
  laravel:
    driver: bridge
